#!/usr/bin/env bash
# configures an Ubuntu machine with nginx
# FILE="/etc/nginx/sites-available/default"
# ERRORFILE="/usr/share/nginx/html/404error.html"

# REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/dQw4w9WgXcQ;\n\t}\n"
# ERRORREDIRECT="\n\terror_page 404 /404error.html;\n\tlocation = /404error.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
# CUSTOMHEADER='\n\tadd_header X-Served-By $hostname;\n'

# STRING="Hello World!"
# FOUR="Ceci n'est pas une page"

# apt-get -y update
# apt-get -y install nginx
# ufw allow 'Nginx HTTP'
# echo "$STRING" > /var/www/html/index.nginx-debian.html
# sed -i "37i\ $REDIRECT" "$FILE"

# echo "$FOUR" > "$ERRORFILE"
# sed -i "37i\ $ERRORREDIRECT" "$FILE"

# sed -i "37i\ $CUSTOMHEADER" "$FILE"
# Restart nginx server

function configure_and_install_nginx_server(){
    sudo apt-get update
    sudo apt-get -y install nginx
    sudo chown -R "$USER":"$USER" /var/www/html/
    echo 'Hello World!' > /var/www/html/index.html
    sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/
    server_conf="server {
                listen 80 default_server;
                listen [::]:80 default_server;
                root /var/www/html;
                index index.html index.htm index.nginx-debian.html;
                server_name _;
                add_header X-Served-By \$hostname;
                location / {
                    try_files \$uri \$uri/ =404;
                }
                location /redirect_me {
                    rewrite ^ https://youtube.com/watch?v=QH2-TGUlwu4 permanent;
                }
                error_page 404 /404.html;
                location = /404.html {
                    internal;
                }
            }"
    echo -e "$server_conf" > /etc/nginx/sites-available/default
    if [[ $(pgrep nginx) ]]; then
        sudo nginx -s reload
    else
        sudo service nginx start
    fi
}
configure_and_install_nginx_server;
